// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcHeader.proto
// Protobuf C++ Version: 6.30.2

#include "rpcHeader.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace myrpc {

inline constexpr myRpcHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        service_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        method_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        args_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR myRpcHeader::myRpcHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(myRpcHeader_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct myRpcHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR myRpcHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~myRpcHeaderDefaultTypeInternal() {}
  union {
    myRpcHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 myRpcHeaderDefaultTypeInternal _myRpcHeader_default_instance_;
}  // namespace myrpc
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_rpcHeader_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rpcHeader_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpcHeader_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::myrpc::myRpcHeader, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::myrpc::myRpcHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::myrpc::myRpcHeader, _impl_.service_name_),
        PROTOBUF_FIELD_OFFSET(::myrpc::myRpcHeader, _impl_.method_name_),
        PROTOBUF_FIELD_OFFSET(::myrpc::myRpcHeader, _impl_.args_size_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::myrpc::myRpcHeader)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::myrpc::_myRpcHeader_default_instance_._instance,
};
const char descriptor_table_protodef_rpcHeader_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017rpcHeader.proto\022\005myrpc\"K\n\013myRpcHeader\022"
    "\024\n\014service_name\030\001 \001(\014\022\023\n\013method_name\030\002 \001"
    "(\014\022\021\n\targs_size\030\003 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_rpcHeader_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpcHeader_2eproto = {
    false,
    false,
    109,
    descriptor_table_protodef_rpcHeader_2eproto,
    "rpcHeader.proto",
    &descriptor_table_rpcHeader_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rpcHeader_2eproto::offsets,
    file_level_enum_descriptors_rpcHeader_2eproto,
    file_level_service_descriptors_rpcHeader_2eproto,
};
namespace myrpc {
// ===================================================================

class myRpcHeader::_Internal {
 public:
  using HasBits =
      decltype(std::declval<myRpcHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_._has_bits_);
};

myRpcHeader::myRpcHeader(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, myRpcHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:myrpc.myRpcHeader)
}
PROTOBUF_NDEBUG_INLINE myRpcHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::myrpc::myRpcHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        service_name_(arena, from.service_name_),
        method_name_(arena, from.method_name_) {}

myRpcHeader::myRpcHeader(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const myRpcHeader& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, myRpcHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  myRpcHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.args_size_ = from._impl_.args_size_;

  // @@protoc_insertion_point(copy_constructor:myrpc.myRpcHeader)
}
PROTOBUF_NDEBUG_INLINE myRpcHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        service_name_(arena),
        method_name_(arena) {}

inline void myRpcHeader::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.args_size_ = {};
}
myRpcHeader::~myRpcHeader() {
  // @@protoc_insertion_point(destructor:myrpc.myRpcHeader)
  SharedDtor(*this);
}
inline void myRpcHeader::SharedDtor(MessageLite& self) {
  myRpcHeader& this_ = static_cast<myRpcHeader&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.service_name_.Destroy();
  this_._impl_.method_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL myRpcHeader::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) myRpcHeader(arena);
}
constexpr auto myRpcHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(myRpcHeader),
                                            alignof(myRpcHeader));
}
constexpr auto myRpcHeader::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_myRpcHeader_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &myRpcHeader::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<myRpcHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &myRpcHeader::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<myRpcHeader>(), &myRpcHeader::ByteSizeLong,
              &myRpcHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_._cached_size_),
          false,
      },
      &myRpcHeader::kDescriptorMethods,
      &descriptor_table_rpcHeader_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull myRpcHeader_class_data_ =
        myRpcHeader::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL myRpcHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&myRpcHeader_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(myRpcHeader_class_data_.tc_table);
  return myRpcHeader_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
myRpcHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    myRpcHeader_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::myrpc::myRpcHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes service_name = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.service_name_)}},
    // bytes method_name = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.method_name_)}},
    // int32 args_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(myRpcHeader, _impl_.args_size_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.args_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes service_name = 1;
    {PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.service_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes method_name = 2;
    {PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.method_name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 args_size = 3;
    {PROTOBUF_FIELD_OFFSET(myRpcHeader, _impl_.args_size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void myRpcHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:myrpc.myRpcHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.service_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.method_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.args_size_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL myRpcHeader::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const myRpcHeader& this_ = static_cast<const myRpcHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL myRpcHeader::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const myRpcHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:myrpc.myRpcHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes service_name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_service_name().empty()) {
      const std::string& _s = this_._internal_service_name();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes method_name = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_method_name().empty()) {
      const std::string& _s = this_._internal_method_name();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // int32 args_size = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_args_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_args_size(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myrpc.myRpcHeader)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t myRpcHeader::ByteSizeLong(const MessageLite& base) {
  const myRpcHeader& this_ = static_cast<const myRpcHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t myRpcHeader::ByteSizeLong() const {
  const myRpcHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:myrpc.myRpcHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // bytes service_name = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_service_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_service_name());
      }
    }
    // bytes method_name = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_method_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_method_name());
      }
    }
    // int32 args_size = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_args_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_args_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void myRpcHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<myRpcHeader*>(&to_msg);
  auto& from = static_cast<const myRpcHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myrpc.myRpcHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_service_name().empty()) {
        _this->_internal_set_service_name(from._internal_service_name());
      } else {
        if (_this->_impl_.service_name_.IsDefault()) {
          _this->_internal_set_service_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_method_name().empty()) {
        _this->_internal_set_method_name(from._internal_method_name());
      } else {
        if (_this->_impl_.method_name_.IsDefault()) {
          _this->_internal_set_method_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_args_size() != 0) {
        _this->_impl_.args_size_ = from._impl_.args_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void myRpcHeader::CopyFrom(const myRpcHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myrpc.myRpcHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void myRpcHeader::InternalSwap(myRpcHeader* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_name_, &other->_impl_.service_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_name_, &other->_impl_.method_name_, arena);
  swap(_impl_.args_size_, other->_impl_.args_size_);
}

::google::protobuf::Metadata myRpcHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace myrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rpcHeader_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
